spring:
  application:
    name: ashs-alumni-backend

  mvc:
    problemdetails:
      enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_ISSUER_URI:http://localhost:8079/realms/ashs-alumni}

  # Flyway configuration
  flyway:
    enabled: true
    locations: classpath:db/migration


  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# Actuator configuration


management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus"
  metrics:
    tags:
      application: ${spring.application.name}

# Server configuration
server:
  port: ${SERVER_PORT:8080}


# Logging configuration

keycloak:
  auth-server-url: ${KC_AUTH_SERVER_URL:http://localhost:8079}
  realm: ${KC_REALM:ashs-alumni}
  frontend-client-id: ${KC_FRONTEND_CLIENT_ID:angular-frontend}
  redirect-url: ${KC_REDIRECT_URL:http://localhost:4200/*}


twilio:
  account-sid: ${TWILIO_ACCOUNT_SID}
  auth-token: ${TWILIO_AUTH_TOKEN}
  phone-number: ${TWILIO_PHONE_NUMBER}
  webhook-url: ${TWILIO_WEBHOOK_URL:https://your-domain.com/api/webhooks/twilio/status}

logging:
  level:
    # Si LOGGING_LEVEL_ROOT n'est pas défini, on utilise WARN par défaut
    root: ${LOGGING_LEVEL_ROOT:WARN}
    # Si LOGGING_LEVEL_APP n'est pas défini, on utilise INFO par défaut
    fr.hoenheimsports.app: ${LOGGING_LEVEL_APP:INFO}
    # Si LOGGING_LEVEL_DOMAIN n'est pas défini, on utilise INFO par défaut
    fr.hoenheimsports.domain: ${LOGGING_LEVEL_DOMAIN:INFO}