spring:
  config:
    activate:
      on-profile: prod

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate # Très important : ne jamais utiliser 'update' ou 'create' en prod


  security:
    oauth2:
      resourceserver:
        jwt:
          # URL Keycloak de production (souvent HTTPS)
          issuer-uri: ${OAUTH2_ISSUER_URI}
          jwk-set-uri: ${OAUTH2_JWK_SET_URI}

  # Docker Compose désactivé en prod (l'infra est gérée autrement, ex: Kubernetes, Docker Swarm)
  docker:
    compose:
      enabled: false

app:
  cors:
    allowed-origins: http://localhost:80,http://localhost

logging:
  level:
    root: WARN
    com.ashs.alumni: INFO