global:
  scrape_interval: 15s # Intervalle entre chaque collecte par Prometheus

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['alumni-ashs-backend:8080']